In [1]:
import pandas as pd

In [2]:
df_cat = pd.read_csv('./Датасеты/Catalog.csv')

In [3]:
df_ex = pd.read_csv('./Датасеты/Examples.csv')

In [4]:
df_ex = df_ex.append(pd.read_csv('./Датасеты/Examples_2.csv'))

In [5]:
df_cat.head()

,Unnamed: 0,doc_id,p100a,p245a,p260a,p260b,p260c,p490a,p650a,p084a,p521a
0,0,1,Устинова Татьяна Витальевна,Призрак Канта,Москва,Эксмо,2018,Татьяна Устинова. Первая среди лучших,Художественная литература ; Российский детектив,84(2Рос)6,16+
1,1,2,NaN,Наука и жизнь,Москва,АНО Редакция журнала «Наука и жизнь»,1938-,NaN,Наука. Науковедение,72,12+
2,2,3,NaN,Наука и жизнь,NaN,NaN,2018,NaN,Наука. Науковедение,72,12+
3,3,4,NaN,Наука и жизнь,NaN,NaN,2018,NaN,Наука. Науковедение,72,12+
4,4,5,NaN,Наука и жизнь,NaN,NaN,2018,NaN,Наука. Науковедение,72,12+

In [6]:
df_ex.head()

,Unnamed: 0,Идентификатор экземпляра,ИД Каталожной записи,Инвентарный номер,Штрих-код,Раздел знаний,Идентификатор сиглы
0,0,12488544,1,09:0000120386,980007854120,84(2Рос=Рус)6,314.0
1,1,12488546,1,09:0000152427,980010247056,84(2Рос=Рус)6,320.0
2,2,12488542,1,09:0000240622,980000737154,84(2Рос=Рус)6,306.0
3,3,13671389,1,09:0000278133,980005475303,84(2Рос=Рус)6,308.0
4,4,7625486,1,05:0000257728,580001931461,84(2Рос=Рус)6,293.0

In [7]:
df_ex = df_ex.merge(df_cat, left_on=['ИД Каталожной записи'], right_on='doc_id')

In [8]:
df_vyd = pd.read_csv("./Датасеты/Vydacha_1.csv")

/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [9]:
df_vyd = df_vyd.append(pd.read_csv("./Датасеты/Vydacha_2.csv"))

In [10]:
df_vyd.shape

(11420807, 11)

In [11]:
df_vyd.head()

,Unnamed: 0,ИД выдачи,ИД читателя,Инвентарный номер,Штрих-код,Дата выдачи,Дата сдачи (предполагаемая),Состояние,Unnamed: 7,Состояния,Unnamed: 9
0,0,1,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6545,NaN,6544.0,На руках
1,1,2,179,03:0000005761,381000196420,2018-04-13 15:00:00,2018-04-16 15:00:00,6548,NaN,6545.0,Переоформлен
2,2,3,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6545,NaN,6548.0,Размещен в фонде
3,3,4,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6545,NaN,NaN,NaN
4,4,5,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6548,NaN,NaN,NaN

In [12]:
df_vyd = df_vyd.merge(df_ex, on='Штрих-код')

In [13]:
df_vyd.shape

(10877130, 28)

In [14]:
df_vyd.head()

,Unnamed: 0,ИД выдачи,ИД читателя,Инвентарный номер_x,Штрих-код,Дата выдачи,Дата сдачи (предполагаемая),Состояние,Unnamed: 7,Состояния,...,doc_id,p100a,p245a,p260a,p260b,p260c,p490a,p650a,p084a,p521a
0,0,1,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6545,NaN,6544.0,...,5190,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN
1,2,3,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6545,NaN,6548.0,...,5190,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN
2,3,4,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6545,NaN,NaN,...,5190,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN
3,4,5,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6548,NaN,NaN,...,5190,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN
4,5,6,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6548,NaN,NaN,...,5190,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN

In [15]:
df_vyd['rating'] = 1

In [16]:
df_vyd.columns

Index(['Unnamed: 0', 'ИД выдачи', 'ИД читателя', 'Инвентарный номер_x',
       'Штрих-код', 'Дата выдачи', 'Дата сдачи (предполагаемая)', 'Состояние',
       'Unnamed: 7', 'Состояния', 'Unnamed: 9', 'Unnamed: 0_x',
       'Идентификатор экземпляра', 'ИД Каталожной записи',
       'Инвентарный номер_y', 'Раздел знаний', 'Идентификатор сиглы',
       'Unnamed: 0_y', 'doc_id', 'p100a', 'p245a', 'p260a', 'p260b', 'p260c',
       'p490a', 'p650a', 'p084a', 'p521a', 'rating'],
      dtype='object')

In [17]:
from tqdm import tqdm

In [21]:
def update_weight(group):
    weights = group['p650a'].value_counts(normalize=True).to_dict()
    group['rating'] = group['p650a'].map(weights) 
    return group

In [19]:
tqdm.pandas()

/usr/local/lib/python3.9/site-packages/tqdm/std.py:703: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

In [22]:
df_vyd = df_vyd.groupby('ИД читателя').progress_apply(update_weight)

100%|██████████| 446860/446860 [28:17<00:00, 263.30it/s]

In [24]:
df_vyd.columns

Index(['Unnamed: 0', 'ИД выдачи', 'ИД читателя', 'Инвентарный номер_x',
       'Штрих-код', 'Дата выдачи', 'Дата сдачи (предполагаемая)', 'Состояние',
       'Unnamed: 7', 'Состояния', 'Unnamed: 9', 'Unnamed: 0_x',
       'Идентификатор экземпляра', 'ИД Каталожной записи',
       'Инвентарный номер_y', 'Раздел знаний', 'Идентификатор сиглы',
       'Unnamed: 0_y', 'doc_id', 'p100a', 'p245a', 'p260a', 'p260b', 'p260c',
       'p490a', 'p650a', 'p084a', 'p521a', 'rating'],
      dtype='object')

In [25]:
df_vyd.head()

,Unnamed: 0,ИД выдачи,ИД читателя,Инвентарный номер_x,Штрих-код,Дата выдачи,Дата сдачи (предполагаемая),Состояние,Unnamed: 7,Состояния,...,p100a,p245a,p260a,p260b,p260c,p490a,p650a,p084a,p521a,rating
0,0,1,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6545,NaN,6544.0,...,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN,0.875
1,2,3,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6545,NaN,6548.0,...,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN,0.875
2,3,4,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6545,NaN,NaN,...,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN,0.875
3,4,5,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6548,NaN,NaN,...,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN,0.875
4,5,6,179,03:0000005767,381000177719,2018-04-13 15:00:00,2018-04-13 15:00:00,6548,NaN,NaN,...,Семенова Мария Васильевна,Год Людоеда,Москва ; Санкт-Петербург,АСТ ; Азбука,2000,NaN,Художественная литература,84(2Рос)6,NaN,0.875

In [33]:
df_vyd.p521a.unique()

array([nan, '16+', '12+', '0+', '18+', '6+', '16+ ; 18+', '6+ ; 0+',
       '0+ ; 6+', '6+ ; 12+'], dtype=object)

In [36]:
df_vyd[['ИД выдачи', 'ИД читателя', 'Инвентарный номер_x',
       'Штрих-код', 'Идентификатор экземпляра', 'ИД Каталожной записи',
       'doc_id', 'p100a', 'p245a', 'p650a', 'p521a', 'rating']].to_csv('vydacha_rated.csv')

In [37]:
pd.read_csv('vydacha_rated.csv')

,Unnamed: 0,ИД выдачи,ИД читателя,Инвентарный номер_x,Штрих-код,Идентификатор экземпляра,ИД Каталожной записи,doc_id,p100a,p245a,p650a,p521a,rating
0,0,1,179,03:0000005767,381000177719,30266,5190,5190,Семенова Мария Васильевна,Год Людоеда,Художественная литература,NaN,0.875000
1,1,3,179,03:0000005767,381000177719,30266,5190,5190,Семенова Мария Васильевна,Год Людоеда,Художественная литература,NaN,0.875000
2,2,4,179,03:0000005767,381000177719,30266,5190,5190,Семенова Мария Васильевна,Год Людоеда,Художественная литература,NaN,0.875000
3,3,5,179,03:0000005767,381000177719,30266,5190,5190,Семенова Мария Васильевна,Год Людоеда,Художественная литература,NaN,0.875000
4,4,6,179,03:0000005767,381000177719,30266,5190,5190,Семенова Мария Васильевна,Год Людоеда,Художественная литература,NaN,0.875000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10877125,10877125,11423335,388940,09:0000722640,980009027645,15082507,240179,240179,Курлат Феликс Львович,Москва. От центра до окраин,История России,NaN,0.043478
10877126,10877126,11423356,57347,01:0000813506,181009423486,4106819,370353,370353,Мамин-Сибиряк Дмитрий Наркисович,Серая шейка,Художественная литература,NaN,0.521739
10877127,10877127,11423371,452490,09:0000140762,900001407627,13200176,1216514,1216514,Функе Корнелия,Бесстрашная Игрэйн,Художественная литература,0+,0.311475
10877128,10877128,11423381,566212,08:0000469319,880004721237,9889224,336559,336559,Линдгрен Астрид,Братья Львиное сердце; Кале Блумквист и Расмус,Художественная литература,NaN,1.000000
10877129,10877129,11423382,435542,09:0000722644,980009027652,15082547,240179,240179,Курлат Феликс Львович,Москва. От центра до окраин,История России,NaN,0.045082